---
dist:
  name: otelcol
  description: OTel collector for CND o11y server
  output_path: ./otelcol

extensions:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension v0.123.0

receivers:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/filelogreceiver v0.123.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/hostmetricsreceiver v0.123.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/postgresqlreceiver v0.123.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver v0.123.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/redisreceiver v0.123.0
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.123.0

processors:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/attributesprocessor v0.123.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourcedetectionprocessor v0.123.0
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.123.0

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.123.0
  - gomod: go.opentelemetry.io/collector/exporter/otlphttpexporter v0.123.0

providers:
  - gomod: go.opentelemetry.io/collector/confmap/provider/envprovider v1.29.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/fileprovider v1.29.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpsprovider v1.29.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/yamlprovider v1.29.0
