{
 "title": "CNDS2025 Proposal",
 "tags": [ "CNDS2025" ],
 "time": { "from": "2025-02-19T15:00:00.000Z", "to": "2025-05-22T14:59:59.000Z" },
 "panels": [
  {
   "title": "プロポーザル数",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dreamkast_talks_count{conference_id=\"13\"}"
    }
   ]
  },
  {
   "title": "プロポーザル数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "dreamkast_talks_count{conference_id=\"13\"}"
    }
   ]
  },
  {
   "title": "受講者レベル",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dreamkast_talk_difficulties_count{conference_id=\"13\", talk_difficulty_name=~\"上級者|中級者|初級者\"}",
     "legendFormat": "{{talk_difficulty_name}}"
    }
   ]
  },
  {
   "title": "想定受講者",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(dreamkast_select_proposal_items{conference_id=\"13\",proposal_items_label=\"assumed_visitor\",proposal_items_params=~\".*179.*\"})",
     "legendFormat": "Architect - システム設計"
    },
    {
     "expr": "count(dreamkast_select_proposal_items{conference_id=\"13\",proposal_items_label=\"assumed_visitor\",proposal_items_params=~\".*180.*\"})",
     "legendFormat": "developer - システム開発"
    },
    {
     "expr": "count(dreamkast_select_proposal_items{conference_id=\"13\",proposal_items_label=\"assumed_visitor\",proposal_items_params=~\".*181.*\"})",
     "legendFormat": "app-developer - アプリケーション開発"
    },
    {
     "expr": "count(dreamkast_select_proposal_items{conference_id=\"13\",proposal_items_label=\"assumed_visitor\",proposal_items_params=~\".*182.*\"})",
     "legendFormat": "operator/sys-admin - 運用管理/システム管理"
    },
    {
     "expr": "count(dreamkast_select_proposal_items{conference_id=\"13\",proposal_items_label=\"assumed_visitor\",proposal_items_params=~\".*183.*\"})",
     "legendFormat": "CxO/biz - ビジネス層"
    },
    {
     "expr": "count(dreamkast_select_proposal_items{conference_id=\"13\",proposal_items_label=\"assumed_visitor\",proposal_items_params=~\".*184.*\"})",
     "legendFormat": "その他"
    }
   ]
  },
  {
   "title": "実行フェーズ",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (dreamkast_select_proposal_items{conference_id=\"13\", proposal_items_label=\"execution_phase\", proposal_items_params=~\".*185.*\"})",
     "legendFormat": "Dev/QA（開発環境）"
    },
    {
     "expr": "count (dreamkast_select_proposal_items{conference_id=\"13\", proposal_items_label=\"execution_phase\", proposal_items_params=~\".*186.*\"})",
     "legendFormat": "PoC（検証）"
    },
    {
     "expr": "count (dreamkast_select_proposal_items{conference_id=\"13\", proposal_items_label=\"execution_phase\", proposal_items_params=~\".*187.*\"})",
     "legendFormat": "Production（本番環境）"
    },
    {
     "expr": "count (dreamkast_select_proposal_items{conference_id=\"13\", proposal_items_label=\"execution_phase\", proposal_items_params=~\".*188.*\"})",
     "legendFormat": "Other"
    }
   ]
  },
  {
   "title": "登壇方法",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (dreamkast_select_proposal_items{conference_id=\"13\", proposal_items_label=\"presentation_method\", proposal_items_params=~\".*193.*\"})",
     "legendFormat": "現地登壇"
    },
    {
     "expr": "count (dreamkast_select_proposal_items{conference_id=\"13\", proposal_items_label=\"presentation_method\", proposal_items_params=~\".*194.*\"})",
     "legendFormat": "事前収録"
    }
   ]
  },
  {
   "title": "スライドと動画の公開可否",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (dreamkast_select_proposal_items{conference_id=\"13\", proposal_items_label=\"whether_it_can_be_published\", proposal_items_params=~\".*189.*\"})",
     "legendFormat": "All okay - スライド・動画両方ともに公開可"
    },
    {
     "expr": "count (dreamkast_select_proposal_items{conference_id=\"13\", proposal_items_label=\"whether_it_can_be_published\", proposal_items_params=~\".*190.*\"})",
     "legendFormat": "Only Slide - スライドのみ公開可"
    },
    {
     "expr": "count (dreamkast_select_proposal_items{conference_id=\"13\", proposal_items_label=\"whether_it_can_be_published\", proposal_items_params=~\".*191.*\"})",
     "legendFormat": "NG - いずれも公開不可（来場者限定のコンテンツ）"
    },
    {
     "expr": "count (dreamkast_select_proposal_items{conference_id=\"13\", proposal_items_label=\"whether_it_can_be_published\", proposal_items_params=~\".*192.*\"})",
     "legendFormat": "その他"
    }
   ]
  },
  {
   "title": "セッション時間",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (dreamkast_select_proposal_items{conference_id=\"13\", proposal_items_label=\"session_time\", proposal_items_params=~\".*195.*\"})",
     "legendFormat": "40min (full session)"
    },
    {
     "expr": "count (dreamkast_select_proposal_items{conference_id=\"13\", proposal_items_label=\"session_time\", proposal_items_params=~\".*196.*\"})",
     "legendFormat": "20min (for keynote)"
    }
   ]
  },
  {
   "title": "言語",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (dreamkast_select_proposal_items{conference_id=\"13\", proposal_items_label=\"language\", proposal_items_params=~\".*197.*\"})",
     "legendFormat": "JP"
    },
    {
     "expr": "count (dreamkast_select_proposal_items{conference_id=\"13\", proposal_items_label=\"language\", proposal_items_params=~\".*198.*\"})",
     "legendFormat": "EN"
    }
   ]
  }
 ]
}