{
 "title": "CNDS2024 Proposal",
 "time": { "from": "2024-03-08T00:00:00.000Z", "to": "2024-04-08T23:59:59.000Z" },
 "panels": [
  {
   "title": "プロポーザル数",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count (dreamkast_talks_id)" }
   ]
  },
  {
   "title": "プロポーザル数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "count (dreamkast_talks_id)" }
   ]
  },
  {
   "title": "受講者レベル",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(talk_difficulty) (dreamkast_talks_id{talk_difficulty=~\"上級者|中級者|初級者\"})",
     "legendFormat": "{{talk_difficulty}}"
    }
   ]
  },
  {
   "title": "想定受講者",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (dreamkast_proposal_items_talk_id{label=\"assumed_visitor\", params=~\".*140.*\"})",
     "legendFormat": "Architect - システム設計"
    },
    {
     "expr": "count (dreamkast_proposal_items_talk_id{label=\"assumed_visitor\", params=~\".*141.*\"})",
     "legendFormat": "developer - システム開発"
    },
    {
     "expr": "count (dreamkast_proposal_items_talk_id{label=\"assumed_visitor\", params=~\".*142.*\"})",
     "legendFormat": "app-developer - アプリケーション開発"
    },
    {
     "expr": "count (dreamkast_proposal_items_talk_id{label=\"assumed_visitor\", params=~\".*143.*\"})",
     "legendFormat": "operator/sys-admin - 運用管理/システム管理"
    },
    {
     "expr": "count (dreamkast_proposal_items_talk_id{label=\"assumed_visitor\", params=~\".*144.*\"})",
     "legendFormat": "CxO/biz - ビジネス層"
    },
    {
     "expr": "count (dreamkast_proposal_items_talk_id{label=\"assumed_visitor\", params=~\".*145.*\"})",
     "legendFormat": "その他"
    }
   ]
  },
  {
   "title": "実行フェーズ",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(dreamkast_proposal_items_talk_id{label=\"execution_phase\", params=~\".*146.*\"})",
     "legendFormat": "Dev/QA（開発環境）"
    },
    {
     "expr": "count(dreamkast_proposal_items_talk_id{label=\"execution_phase\", params=~\".*147.*\"})",
     "legendFormat": "PoC（検証）"
    },
    {
     "expr": "count(dreamkast_proposal_items_talk_id{label=\"execution_phase\", params=~\".*148.*\"})",
     "legendFormat": "Production（本番環境）"
    },
    {
     "expr": "count(dreamkast_proposal_items_talk_id{label=\"execution_phase\", params=~\".*149.*\"})",
     "legendFormat": "Other"
    }
   ]
  },
  {
   "title": "登壇方法",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (dreamkast_proposal_items_talk_id{label=\"presentation_method\", params=~\".*154.*\"})",
     "legendFormat": "現地登壇"
    },
    {
     "expr": "count (dreamkast_proposal_items_talk_id{label=\"presentation_method\", params=~\".*155.*\"})",
     "legendFormat": "事前収録"
    }
   ]
  },
  {
   "title": "スライドと動画の公開可否",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (dreamkast_proposal_items_talk_id{label=\"whether_it_can_be_published\", params=~\".*150.*\"})",
     "legendFormat": "All okay - スライド・動画両方ともに公開可"
    },
    {
     "expr": "count (dreamkast_proposal_items_talk_id{label=\"whether_it_can_be_published\", params=~\".*151.*\"})",
     "legendFormat": "Only Slide - スライドのみ公開可"
    },
    {
     "expr": "count (dreamkast_proposal_items_talk_id{label=\"whether_it_can_be_published\", params=~\".*152.*\"})",
     "legendFormat": "NG - いずれも公開不可（来場者限定のコンテンツ）"
    },
    {
     "expr": "count (dreamkast_proposal_items_talk_id{label=\"whether_it_can_be_published\", params=~\".*153.*\"})",
     "legendFormat": "その他"
    }
   ]
  },
  {
   "title": "セッション時間",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (dreamkast_proposal_items_talk_id{label=\"session_time\", params=~\".*156.*\"})",
     "legendFormat": "40min (full session)"
    }
   ]
  },
  {
   "title": "言語",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (dreamkast_proposal_items_talk_id{label=\"language\", params=~\".*158.*\"})",
     "legendFormat": "EN"
    },
    {
     "expr": "count (dreamkast_proposal_items_talk_id{label=\"language\", params=~\".*157.*\"})",
     "legendFormat": "JP"
    }
   ]
  }
 ]
}