{
 "title": "CNDW2025 Proposal",
 "description": "CNDW2025のプロポーザルの募集状況を可視化したダッシュボードです。",
 "time": { "from": "2025-08-31T15:00:00.000Z", "to": "2025-09-21T14:59:59.000Z" },
 "panels": [
  {
   "title": "プロポーザル数",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dreamkast_talks_count{conference_id=\"14\"}"
    }
   ]
  },
  {
   "title": "プロポーザル数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "dreamkast_talks_count{conference_id=\"14\"}"
    }
   ]
  },
  {
   "title": "受講者レベル",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dreamkast_talk_difficulties_count{conference_id=\"14\", talk_difficulty_name=~\"上級者|中級者|初級者\"}",
     "legendFormat": "{{talk_difficulty_name}}"
    }
   ]
  },
  {
   "title": "想定受講者",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(dreamkast_select_proposal_items{conference_id=\"14\",proposal_items_label=\"assumed_visitor\",proposal_items_params=~\".*199.*\"})",
     "legendFormat": "Architect - システム設計"
    },
    {
     "expr": "count(dreamkast_select_proposal_items{conference_id=\"14\",proposal_items_label=\"assumed_visitor\",proposal_items_params=~\".*200.*\"})",
     "legendFormat": "Developer - システム開発"
    },
    {
     "expr": "count(dreamkast_select_proposal_items{conference_id=\"14\",proposal_items_label=\"assumed_visitor\",proposal_items_params=~\".*201.*\"})",
     "legendFormat": "App-Developer - アプリケーション開発"
    },
    {
     "expr": "count(dreamkast_select_proposal_items{conference_id=\"14\",proposal_items_label=\"assumed_visitor\",proposal_items_params=~\".*202.*\"})",
     "legendFormat": "Operator/Sys-Admin - 運用管理/システム管理"
    },
    {
     "expr": "count(dreamkast_select_proposal_items{conference_id=\"14\",proposal_items_label=\"assumed_visitor\",proposal_items_params=~\".*203.*\"})",
     "legendFormat": "CxO/Biz - ビジネス層"
    },
    {
     "expr": "count(dreamkast_select_proposal_items{conference_id=\"14\",proposal_items_label=\"assumed_visitor\",proposal_items_params=~\".*204.*\"})",
     "legendFormat": "その他"
    }
   ]
  },
  {
   "title": "実行フェーズ",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (dreamkast_select_proposal_items{conference_id=\"14\", proposal_items_label=\"execution_phase\", proposal_items_params=~\".*205.*\"})",
     "legendFormat": "Dev/QA（開発環境）"
    },
    {
     "expr": "count (dreamkast_select_proposal_items{conference_id=\"14\", proposal_items_label=\"execution_phase\", proposal_items_params=~\".*206.*\"})",
     "legendFormat": "PoC（検証）"
    },
    {
     "expr": "count (dreamkast_select_proposal_items{conference_id=\"14\", proposal_items_label=\"execution_phase\", proposal_items_params=~\".*207.*\"})",
     "legendFormat": "Production（本番環境）"
    },
    {
     "expr": "count (dreamkast_select_proposal_items{conference_id=\"14\", proposal_items_label=\"execution_phase\", proposal_items_params=~\".*208.*\"})",
     "legendFormat": "Other"
    }
   ]
  },
  {
   "title": "登壇方法",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (dreamkast_select_proposal_items{conference_id=\"14\", proposal_items_label=\"presentation_method\", proposal_items_params=~\".*213.*\"})",
     "legendFormat": "現地登壇"
    },
    {
     "expr": "count (dreamkast_select_proposal_items{conference_id=\"14\", proposal_items_label=\"presentation_method\", proposal_items_params=~\".*214.*\"})",
     "legendFormat": "事前収録"
    }
   ]
  },
  {
   "title": "スライドと動画の公開可否",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (dreamkast_select_proposal_items{conference_id=\"14\", proposal_items_label=\"whether_it_can_be_published\", proposal_items_params=~\".*209.*\"})",
     "legendFormat": "All okay - スライド・動画両方ともに公開可"
    },
    {
     "expr": "count (dreamkast_select_proposal_items{conference_id=\"14\", proposal_items_label=\"whether_it_can_be_published\", proposal_items_params=~\".*210.*\"})",
     "legendFormat": "Only Slide - スライドのみ公開可"
    },
    {
     "expr": "count (dreamkast_select_proposal_items{conference_id=\"14\", proposal_items_label=\"whether_it_can_be_published\", proposal_items_params=~\".*211.*\"})",
     "legendFormat": "NG - いずれも公開不可（来場者限定のコンテンツ）"
    },
    {
     "expr": "count (dreamkast_select_proposal_items{conference_id=\"14\", proposal_items_label=\"whether_it_can_be_published\", proposal_items_params=~\".*212.*\"})",
     "legendFormat": "その他"
    }
   ]
  },
  {
   "title": "セッション時間",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (dreamkast_select_proposal_items{conference_id=\"14\", proposal_items_label=\"session_time\", proposal_items_params=~\".*215.*\"})",
     "legendFormat": "40min (full session)"
    },
    {
     "expr": "count (dreamkast_select_proposal_items{conference_id=\"14\", proposal_items_label=\"session_time\", proposal_items_params=~\".*216.*\"})",
     "legendFormat": "20min (for keynote)"
    }
   ]
  },
  {
   "title": "言語",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (dreamkast_select_proposal_items{conference_id=\"14\", proposal_items_label=\"language\", proposal_items_params=~\".*217.*\"})",
     "legendFormat": "JP"
    },
    {
     "expr": "count (dreamkast_select_proposal_items{conference_id=\"14\", proposal_items_label=\"language\", proposal_items_params=~\".*218.*\"})",
     "legendFormat": "EN"
    }
   ]
  }
 ]
}