{
 "title": "クラウドネイティブ会議プロポーザル応募状況",
 "description": "クラウドネイティブ会議のプロポーザルの募集状況を可視化したダッシュボードです。",
 "tags": [
  "クラウドネイティブ会議",
  "CloudNative Days",
  "Proposal",
  "Platform Engineering Kaigi",
  "SRE Kaigi"
 ],
 "time": { "from": "2026-02-01T15:00:00.000Z", "to": "2026-03-01T14:59:59.000Z" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# クラウドネイティブ会議 プロポーザル応募状況\n\nクラウドネイティブ会議の各トラックのプロポーザルの応募状況を可視化したダッシュボードです。ぜひ参考にしてみてください!!\n\nプロポーザルの応募に関しては[こちら](https://kaigi.cloudnativedays.jp/cfp/)から確認できます。"
   }
  },
  { "title": "CloudNativeトラック", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "プロポーザル数",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dreamkast_proposals_by_category_count{conference_id=\"15\", target_conference=\"cnd_category\"}"
    }
   ]
  },
  {
   "title": "プロポーザル数 (推移)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "dreamkast_proposals_by_category_count{conference_id=\"15\", target_conference=\"cnd_category\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "受講者レベル",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dreamkast_talk_difficulties_by_category_count{conference_id=\"15\", target_conference=\"cnd_category\"}",
     "legendFormat": "{{talk_difficulty_name}}"
    }
   ]
  },
  {
   "title": "想定受講者",
   "type": "piechart",
   "description": "想定受講者は複数選択可能のため、参考値としてご覧ください。",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dreamkast_assumed_visitors_by_category_count{conference_id=\"15\", target_conference=\"cnd_category\"}",
     "legendFormat": "{{assumed_visitor_name}}"
    }
   ]
  },
  {
   "title": "実行フェーズ",
   "type": "piechart",
   "description": "実行フェーズは複数選択可能のため、参考値としてご覧ください。",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dreamkast_execution_phases_by_category_count{conference_id=\"15\", target_conference=\"cnd_category\"}",
     "legendFormat": "{{execution_phase_name}}"
    }
   ]
  },
  { "title": "Platform Engineering トラック", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "プロポーザル数",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dreamkast_proposals_by_category_count{conference_id=\"15\", target_conference=\"pek_category\"}"
    }
   ]
  },
  {
   "title": "プロポーザル数 (推移)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "dreamkast_proposals_by_category_count{conference_id=\"15\", target_conference=\"pek_category\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "受講者レベル",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dreamkast_talk_difficulties_by_category_count{conference_id=\"15\", target_conference=\"pek_category\"}",
     "legendFormat": "{{talk_difficulty_name}}"
    }
   ]
  },
  {
   "title": "想定受講者",
   "type": "piechart",
   "description": "想定受講者は複数選択可能のため、参考値としてご覧ください。",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dreamkast_assumed_visitors_by_category_count{conference_id=\"15\", target_conference=\"pek_category\"}",
     "legendFormat": "{{assumed_visitor_name}}"
    }
   ]
  },
  {
   "title": "実行フェーズ",
   "type": "piechart",
   "description": "実行フェーズは複数選択可能のため、参考値としてご覧ください。",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dreamkast_execution_phases_by_category_count{conference_id=\"15\", target_conference=\"pek_category\"}",
     "legendFormat": "{{execution_phase_name}}"
    }
   ]
  },
  { "title": "SRE トラック", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "プロポーザル数",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dreamkast_proposals_by_category_count{conference_id=\"15\", target_conference=\"srek_category\"}"
    }
   ]
  },
  {
   "title": "プロポーザル数 (推移)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "expr": "dreamkast_proposals_by_category_count{conference_id=\"15\", target_conference=\"srek_category\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "受講者レベル",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dreamkast_talk_difficulties_by_category_count{conference_id=\"15\", target_conference=\"srek_category\"}",
     "legendFormat": "{{talk_difficulty_name}}"
    }
   ]
  },
  {
   "title": "想定受講者",
   "type": "piechart",
   "description": "想定受講者は複数選択可能のため、参考値としてご覧ください。",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dreamkast_assumed_visitors_by_category_count{conference_id=\"15\", target_conference=\"srek_category\"}",
     "legendFormat": "{{assumed_visitor_name}}"
    }
   ]
  },
  {
   "title": "実行フェーズ",
   "type": "piechart",
   "description": "実行フェーズは複数選択可能のため、参考値としてご覧ください。",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dreamkast_execution_phases_by_category_count{conference_id=\"15\", target_conference=\"srek_category\"}",
     "legendFormat": "{{execution_phase_name}}"
    }
   ]
  }
 ]
}