x-restart-policy: &restart_policy
  restart: unless-stopped
  logging:
    driver: loki
    options:
      loki-url: "http://loki:3100/loki/api/v1/push"

services:
  loki:
    image: grafana/loki:2.9.5
    expose:
      - "3100"
    volumes:
      - loki-data:/loki
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - https-portal-data:/var/lib/https-portal
    depends_on:
      - loki

volumes:
  loki-data:
    external: true
