apiVersion: 1

datasources:
  # see: https://grafana.com/docs/grafana/latest/administration/provisioning/#plugins
  - name: BigQuery-DS
    type: grafana-bigquery-datasource
    editable: true
    enabled: true
    jsonData:
      authenticationType: jwt
      clientEmail: grafana-bigquery-integration@cloudnativedays-o11y.iam.gserviceaccount.com
      defaultProject: cloudnativedays-o11y
      tokenUri: https://oauth2.googleapis.com/token
      privateKeyPath: /etc/secrets/bigquery.pem
