---
services:
  prometheus:
    logging:
      options:
        loki-url: "https://loki.cloudnativedays.jp/loki/api/v1/push"
    healthcheck:
      interval: "30s"
      timeout: "1m30s"
      retries: 10
      start_period: "10s"
      test: ["cmd", "wget", "http://localhost:9090"]
    volumes:
      - ./stg/prometheus/config/prometheus.yaml:/etc/prometheus/prometheus.yaml
      - ./stg/prometheus/config/web.yaml:/etc/prometheus/web.yaml
  node-exporter:
    logging:
      options:
        loki-url: "https://loki.cloudnativedays.jp/loki/api/v1/push"
