---
extensions:
  health_check:

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  hostmetrics:
    collection_interval: 1m
    scrapers:
      cpu:
      disk:
      filesystem:
      load:
      memory:
      network:
      paging:
  prometheus/grafana:
    config:
      scrape_configs:
        - job_name: grafana
          scrape_interval: 1m
          static_configs:
            - targets: ['localhost:3000']

processors:
  attributes:
    actions:
      - action: upsert
        key: service.namespace
        value: o11y-stacks-stg
      - action: upsert
        key: service.name
        value: o11y-stacks-stg
  attributes/grafana:
    actions:
      - action: upsert
        key: service.namespace
        value: o11y-stacks-stg
      - action: upsert
        key: service.name
        value: grafana
  batch:
    timeout: 1m
  resourcedetection/system:
    detectors: ["system"]
    system:
      hostname_sources: ["os"]

exporters:
  otlp/mackerel:
    endpoint: otlp.mackerelio.com:4317
    compression: gzip
    headers:
      Mackerel-Api-Key: ${env:MACKEREL_APIKEY}

service:
  pipelines:
    # traces:
    #   receivers: [otlp]
    #   processors: [batch]
    #   exporters: [debug]
    metrics:
      receivers: [otlp, hostmetrics]
      processors: [attributes, batch, resourcedetection/system]
      exporters: [otlp/mackerel]
    metrics/grafana:
      receivers: [prometheus/grafana]
      processors: [attributes/grafana, batch]
      exporters: [otlp/mackerel]
    # logs:
    #   receivers: [otlp]
    #   processors: [batch]
    #   exporters: [debug]
  extensions: [health_check]
