services:
  grafana:
    volumes:
      - ./prod/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./prod/grafana/dashboards:/var/lib/grafana/dashboards
      - ./prod/grafana/config/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
      - ./prod/grafana/config/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./prod/grafana/secrets/bigquery.pem:/etc/secrets/bigquery.pem
  loki:
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./prod/loki/config/config.yml:/etc/loki/local-config.yaml
  prometheus:
    volumes:
      - ./prod/prometheus/config/prometheus.yaml:/etc/prometheus/prometheus.yaml
      - ./prod/prometheus/config/web.yaml:/etc/prometheus/web.yaml
  https-portal:
    environment:
      DOMAINS: "grafana.cloudnativedays.jp -> http://grafana:3000, loki.cloudnativedays.jp -> http://loki:3100, prometheus.cloudnativedays.jp -> http://prometheus:9090"
      STAGE: production
