{
 "title": "クラウドネイティブ会議_Dreamkastダッシュボード",
 "tags": [
  "Dreamkast",
  "Prometheus",
  "クラウドネイティブ会議"
 ],
 "time": { "from": "now-1d", "to": "now" },
 "templating": {
  "list": [
   { "name": "queryString", "query": { "query": "label_values(queryString)" } }
  ]
 },
 "panels": [
  { "title": "Dreamkast", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Dreamkastダッシュボード使い方",
   "type": "text",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "# Dreamkastダッシュボード使い方\n\n主に、[クラウドネイティブ会議](https://kaigi.cloudnativedays.jp/)で用いている配信プラットフォーム`Dreamkastのメトリクス`を表示するダッシュボードです。\n\n動画配信のメトリクスに加え、イベントの登録者数などのイベント全体に関わるメトリクスを表示する役割を持ちます。\n\n現在表示しているメトリクスは下記の通りです。\n\n- クラウドネイティブ会議視聴者数: Dreamkastを通して`動画視聴しているユーザ数`を表示しています。\n- 累計チャット数: Dreamkastの動画の横に配置している`チャットへの累計投稿数`を表示しています。\n- クラウドネイティブ会議参加登録者数: `クラウドネイティブ会議に参加登録いただいた人数`を表示しています。"
   }
  },
  {
   "title": "クラウドネイティブ会議_オンライン視聴者数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 9 },
   "targets": [
    { "expr": "sum(dkw_viewer_count)", "legendFormat": "オンライン視聴者数" }
   ]
  },
  {
   "title": "クラウドネイティブ会議 オンライン視聴者数(最新値)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "人" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(dkw_viewer_count)" }
   ]
  },
  {
   "title": "累積チャット数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "max(sum(dreamkast_chat_count) by(instance))",
     "legendFormat": "累積チャット数"
    }
   ]
  },
  {
   "title": "累積チャット数 (最新値)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(sum(dreamkast_chat_count) by(instance))"
    }
   ]
  },
  {
   "title": "CNDW2025参加登録者数",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 18, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "dreamkast_stats_of_registrants_offline{conference_id=\"15\"} + dreamkast_stats_of_registrants_online{conference_id=\"15\"}",
     "legendFormat": "全体"
    },
    {
     "expr": "dreamkast_stats_of_registrants_offline{conference_id=\"15\"}",
     "legendFormat": "オフライン"
    },
    {
     "expr": "dreamkast_stats_of_registrants_online{conference_id=\"15\"}",
     "legendFormat": "オンライン"
    }
   ]
  },
  {
   "title": "クラウドネイティブ会議_登録者数 (最新値)",
   "type": "stat",
   "gridPos": { "h": 13, "w": 6, "x": 18, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dreamkast_stats_of_registrants_offline{conference_id=\"15\"} + dreamkast_stats_of_registrants_online{conference_id=\"15\"}",
     "legendFormat": "クラウドネイティブ会議参加登録数"
    },
    {
     "expr": "max(dreamkast_stats_of_registrants_offline{conference_id=\"15\"})",
     "legendFormat": "オフライン参加者数"
    },
    {
     "expr": "max(dreamkast_stats_of_registrants_online{conference_id=\"15\"})",
     "legendFormat": "オンライン参加者数"
    }
   ]
  }
 ]
}