services:
  loki:
    image: grafana/loki:2.9.5
    expose:
      - "3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./stg/loki/config/config.yml:/etc/loki/local-config.yaml
  https-portal:
    environment:
      DOMAINS: stg.loki.cloudnativedays.jp -> http://loki:3100
      # FIXME: use production
      STAGE: production
