{
 "title": "CloudNativeDays Deep Dive",
 "tags": [
  "CloudNativeDays",
  "GA4",
  "Website"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "このダッシュボードについて",
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# CloudNativeDays Deep Dive\n\nこのダッシュボードは、CloudNativeDaysの[公式サイト](https://cloudnativedays.jp/)の過去60日間のアクセス情報を可視化しています。\n\n一体、どのようなユーザな方たちが見られているのかを少し覗いてみましょう!!\n\n"
   }
  },
  {
   "title": "サイトアクセス数 (国別)",
   "type": "stat",
   "description": "https://cloudnativedays.jp にアクセスされた方を国別に表示しています。",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "US",
     "project": "cloudnativedays-o11y",
     "rawSql": "SELECT\n  NULLIF(geo.country, '') AS country,\n  COUNT(DISTINCT user_pseudo_id) AS users\nFROM\n  `cloudnativedays-o11y.analytics_363617797.events_*`\nWHERE\n  _TABLE_SUFFIX BETWEEN\n    FORMAT_DATE('%Y%m%d', TIMESTAMP_MILLIS(${__from}))\n    AND FORMAT_DATE('%Y%m%d', TIMESTAMP_MILLIS(${__to}))\n  AND geo.country IS NOT NULL\nGROUP BY country\nORDER BY users DESC"
    }
   ]
  },
  {
   "title": "サイトアクセス数 (都道府県別)",
   "type": "piechart",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "US",
     "project": "cloudnativedays-o11y",
     "rawSql": "SELECT\n  NULLIF(geo.region, '') AS region,\n  COUNT(DISTINCT user_pseudo_id) AS users\nFROM\n  `cloudnativedays-o11y.analytics_363617797.events_*`\nWHERE\n  _TABLE_SUFFIX BETWEEN\n    FORMAT_DATE('%Y%m%d', TIMESTAMP_MILLIS(${__from}))\n    AND FORMAT_DATE('%Y%m%d', TIMESTAMP_MILLIS(${__to}))\n  AND geo.country = 'Japan'\n  AND geo.region IS NOT NULL\nGROUP BY region\nORDER BY users DESC"
    }
   ]
  },
  {
   "title": "使用しているデバイス",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "location": "US",
     "project": "cloudnativedays-o11y",
     "rawSql": "SELECT\n  device.category AS device_category,\n  COUNT(DISTINCT user_pseudo_id) AS users\nFROM\n  `cloudnativedays-o11y.analytics_363617797.events_*`\nWHERE\n  _TABLE_SUFFIX BETWEEN\n    FORMAT_DATE('%Y%m%d', TIMESTAMP_MILLIS(${__from}))\n    AND FORMAT_DATE('%Y%m%d', TIMESTAMP_MILLIS(${__to}))\n  AND device.category IS NOT NULL\nGROUP BY device_category\nORDER BY users DESC"
    }
   ]
  },
  {
   "title": "使用しているOS",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "location": "US",
     "project": "cloudnativedays-o11y",
     "rawSql": "SELECT\n  IFNULL(device.operating_system, '') AS OS,\n  COUNT(DISTINCT user_pseudo_id) AS users\nFROM\n  `cloudnativedays-o11y.analytics_363617797.events_*`\nWHERE\n  _TABLE_SUFFIX BETWEEN\n    FORMAT_DATE('%Y%m%d', TIMESTAMP_MILLIS(${__from}))\n    AND FORMAT_DATE('%Y%m%d', TIMESTAMP_MILLIS(${__to}))\n  AND device.operating_system IS NOT NULL\nGROUP BY OS\nORDER BY users DESC"
    }
   ]
  },
  {
   "title": "使用しているブラウザ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "US",
     "project": "cloudnativedays-o11y",
     "rawSql": "SELECT\n  IFNULL(device.web_info.browser, '') AS browsers,\n  COUNT(DISTINCT user_pseudo_id) AS users\nFROM\n  `cloudnativedays-o11y.analytics_363617797.events_*`\nWHERE\n  _TABLE_SUFFIX BETWEEN\n    FORMAT_DATE('%Y%m%d', TIMESTAMP_MILLIS(${__from}))\n    AND FORMAT_DATE('%Y%m%d', TIMESTAMP_MILLIS(${__to}))\n  AND device.web_info.browser IS NOT NULL\nGROUP BY browsers\nORDER BY users DESC"
    }
   ]
  }
 ]
}