{
 "title": "CNDW2024 Proposal",
 "description": "CNDW2024のプロポーザルの募集状況を可視化したダッシュボードです。",
 "time": { "from": "2024-09-24T00:00:00.000Z", "to": "2024-10-14T23:59:59.000Z" },
 "panels": [
  {
   "title": "プロポーザル数",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dreamkast_talks_count{conference_id=\"12\"}"
    }
   ]
  },
  {
   "title": "プロポーザル数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "dreamkast_talks_count{conference_id=\"12\"}"
    }
   ]
  },
  {
   "title": "受講者レベル",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dreamkast_talk_difficulties_count{conference_id=\"12\", talk_difficulty_name=~\"上級者|中級者|初級者\"}",
     "legendFormat": "{{talk_difficulty_name}}"
    }
   ]
  },
  {
   "title": "想定受講者",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(dreamkast_select_proposal_items{conference_id=\"12\",proposal_items_label=\"assumed_visitor\",proposal_items_params=~\".*159.*\"})",
     "legendFormat": "Architect - システム設計"
    },
    {
     "expr": "count(dreamkast_select_proposal_items{conference_id=\"12\",proposal_items_label=\"assumed_visitor\",proposal_items_params=~\".*160.*\"})",
     "legendFormat": "developer - システム開発"
    },
    {
     "expr": "count(dreamkast_select_proposal_items{conference_id=\"12\",proposal_items_label=\"assumed_visitor\",proposal_items_params=~\".*161.*\"})",
     "legendFormat": "app-developer - アプリケーション開発"
    },
    {
     "expr": "count(dreamkast_select_proposal_items{conference_id=\"12\",proposal_items_label=\"assumed_visitor\",proposal_items_params=~\".*162.*\"})",
     "legendFormat": "operator/sys-admin - 運用管理/システム管理"
    },
    {
     "expr": "count(dreamkast_select_proposal_items{conference_id=\"12\",proposal_items_label=\"assumed_visitor\",proposal_items_params=~\".*163.*\"})",
     "legendFormat": "CxO/biz - ビジネス層"
    },
    {
     "expr": "count(dreamkast_select_proposal_items{conference_id=\"12\",proposal_items_label=\"assumed_visitor\",proposal_items_params=~\".*164.*\"})",
     "legendFormat": "その他"
    }
   ]
  },
  {
   "title": "実行フェーズ",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (dreamkast_select_proposal_items{conference_id=\"12\", proposal_items_label=\"execution_phase\", proposal_items_params=~\".*165.*\"})",
     "legendFormat": "Dev/QA（開発環境）"
    },
    {
     "expr": "count (dreamkast_select_proposal_items{conference_id=\"12\", proposal_items_label=\"execution_phase\", proposal_items_params=~\".*166.*\"})",
     "legendFormat": "PoC（検証）"
    },
    {
     "expr": "count (dreamkast_select_proposal_items{conference_id=\"12\", proposal_items_label=\"execution_phase\", proposal_items_params=~\".*167.*\"})",
     "legendFormat": "Production（本番環境）"
    },
    {
     "expr": "count (dreamkast_select_proposal_items{conference_id=\"12\", proposal_items_label=\"execution_phase\", proposal_items_params=~\".*168.*\"})",
     "legendFormat": "Other"
    }
   ]
  },
  {
   "title": "登壇方法",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (dreamkast_select_proposal_items{conference_id=\"12\", proposal_items_label=\"presentation_method\", proposal_items_params=~\".*173.*\"})",
     "legendFormat": "現地登壇"
    },
    {
     "expr": "count (dreamkast_select_proposal_items{conference_id=\"12\", proposal_items_label=\"presentation_method\", proposal_items_params=~\".*174.*\"})",
     "legendFormat": "事前収録"
    }
   ]
  },
  {
   "title": "スライドと動画の公開可否",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (dreamkast_select_proposal_items{conference_id=\"12\", proposal_items_label=\"whether_it_can_be_published\", proposal_items_params=~\".*169.*\"})",
     "legendFormat": "All okay - スライド・動画両方ともに公開可"
    },
    {
     "expr": "count (dreamkast_select_proposal_items{conference_id=\"12\", proposal_items_label=\"whether_it_can_be_published\", proposal_items_params=~\".*170.*\"})",
     "legendFormat": "Only Slide - スライドのみ公開可"
    },
    {
     "expr": "count (dreamkast_select_proposal_items{conference_id=\"12\", proposal_items_label=\"whether_it_can_be_published\", proposal_items_params=~\".*171.*\"})",
     "legendFormat": "NG - いずれも公開不可（来場者限定のコンテンツ）"
    },
    {
     "expr": "count (dreamkast_select_proposal_items{conference_id=\"12\", proposal_items_label=\"whether_it_can_be_published\", proposal_items_params=~\".*172.*\"})",
     "legendFormat": "その他"
    }
   ]
  },
  {
   "title": "セッション時間",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (dreamkast_select_proposal_items{conference_id=\"12\", proposal_items_label=\"session_time\", proposal_items_params=~\".*175.*\"})",
     "legendFormat": "40min (full session)"
    },
    {
     "expr": "count (dreamkast_select_proposal_items{conference_id=\"12\", proposal_items_label=\"session_time\", proposal_items_params=~\".*176.*\"})",
     "legendFormat": "20min (for keynote)"
    }
   ]
  },
  {
   "title": "言語",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (dreamkast_select_proposal_items{conference_id=\"12\", proposal_items_label=\"language\", proposal_items_params=~\".*178.*\"})",
     "legendFormat": "EN"
    },
    {
     "expr": "count (dreamkast_select_proposal_items{conference_id=\"12\", proposal_items_label=\"language\", proposal_items_params=~\".*177.*\"})",
     "legendFormat": "JP"
    }
   ]
  }
 ]
}