{
 "title": "クラウドネイティブ会議プロポーザル応募状況 (CloudNative トラック)",
 "description": "クラウドネイティブ会議のプロポーザル(CloudNative トラック)の募集状況を可視化したダッシュボードです。",
 "tags": [
  "クラウドネイティブ会議",
  "CloudNative Days",
  "Proposal"
 ],
 "time": { "from": "2026-02-01T15:00:00.000Z", "to": "2026-03-01T14:59:59.000Z" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# クラウドネイティブ会議 プロポーザル応募状況 (CloudNative トラック)\n\nクラウドネイティブ会議のCloudNative トラックのプロポーザルの応募状況を可視化したダッシュボードです。ぜひ参考にしてみてください!!\n\n現在のプロポーザルの応募状況は[こちら](https://kaigi.cloudnativedays.jp/cfp/cloudnative/)から確認できます。"
   }
  },
  {
   "title": "プロポーザル数",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dreamkast_proposals_by_category_count{conference_id=\"15\", target_conference=\"cnd_category\"}"
    }
   ]
  },
  {
   "title": "プロポーザル数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "dreamkast_proposals_by_category_count{conference_id=\"15\", target_conference=\"cnd_category\"}"
    }
   ]
  },
  {
   "title": "受講者レベル",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dreamkast_talk_difficulties_by_category_count{conference_id=\"15\", target_conference=\"cnd_category\"}",
     "legendFormat": "{{talk_difficulty_name}}"
    }
   ]
  },
  {
   "title": "想定受講者",
   "type": "piechart",
   "description": "想定受講者は複数選択可能のため、参考値としてご覧ください。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dreamkast_assumed_visitors_by_category_count{conference_id=\"15\", target_conference=\"cnd_category\"}",
     "legendFormat": "{{assumed_visitor_name}}"
    }
   ]
  },
  {
   "title": "実行フェーズ",
   "type": "piechart",
   "description": "実行フェーズは複数選択可能のため、参考値としてご覧ください。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dreamkast_execution_phases_by_category_count{conference_id=\"15\", target_conference=\"cnd_category\"}",
     "legendFormat": "{{execution_phase_name}}"
    }
   ]
  },
  {
   "title": "スライドと動画の公開可否",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dreamkast_publication_permissions_by_category_count{conference_id=\"15\", target_conference=\"cnd_category\"}",
     "legendFormat": "{{publication_permission_name}}"
    }
   ]
  },
  {
   "title": "セッション時間",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dreamkast_session_times_by_category_count{conference_id=\"15\", target_conference=\"cnd_category\"}",
     "legendFormat": "{{session_time_name}}"
    }
   ]
  },
  {
   "title": "言語",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dreamkast_languages_by_category_count{conference_id=\"15\", target_conference=\"cnd_category\"}\n",
     "legendFormat": "{{language_name}}"
    }
   ]
  }
 ]
}